---
title: "Bonanomi_associated_celltype_with_gene_name"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Write here come text

```{r}


#object_clean_new = readRDS("/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/Bonanomi_1287_scRNA_injury/7_bioinfo/Subclustering_mm10_M16_TdTomato_cc_2/seurat_objects/all_cell_types_scBonanomi_full.Rds")



integrated_3TIP <-readRDS("/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/Bonanomi_1287_scRNA_injury/7_bioinfo/EC_subset/3TIP/integrated_EC_3TIP.Rds")

FeaturePlot(integrated_3TIP, "Esr1", split.by = "stim")


integrated = readRDS("/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/Bonanomi_1287_scRNA_injury/7_bioinfo/Subclustering_mm10_M16_TdTomato_cc_2/seurat_objects/all_cell_types_scBonanomi_full.Rds")


FeaturePlot(integrated, "Esr1", split.by = "stim")


#extract cell names for each ident in the EC dataset integrated_3TIP
ARTERIAL <-WhichCells(object=integrated_3TIP, idents="ARTERIAL")
TIP_1 <-WhichCells(object=integrated_3TIP, idents="TIP_1")
TIP_2 <-WhichCells(object=integrated_3TIP, idents="TIP_2")
TIP_3 <-WhichCells(object=integrated_3TIP, idents="TIP_3")
BARR_END_CAP <-WhichCells(object=integrated_3TIP, idents="BARR_END_CAP")
VENOUS_PLVAP_M <-WhichCells(object=integrated_3TIP, idents="VENOUS_PLVAP-")
VENOUS_PLVAP_P <-WhichCells(object=integrated_3TIP, idents="VENOUS_PLVAP+")
CAPILLARY_PLVAP_M <-WhichCells(object=integrated_3TIP, idents="CAPILLARY_PLVAP-")
CAPILLARY_PLVAP_P <-WhichCells(object=integrated_3TIP, idents="CAPILLARY_PLVAP+")

#highligh specific cells in the full dataset integrated
DimPlot(integrated, label=T, cells.highlight=TIP_1, cols.highlight = c("cyan"), cols= "grey")
DimPlot(integrated)

# since the full dataset object lacks TIP_3 cells labels. Assign them.
Idents(object = integrated, cells = TIP_3) <- 'TIP_3'

# check if everything went well
DimPlot(integrated, split.by = "stim")

DefaultAssay(integrated) = "RNA"


object_clean_new <- subset(x = integrated, subset = stim == "1")


DefaultAssay(object_clean_new) = "RNA"

DimPlot(object_clean_new)


FeaturePlot(object_clean_new, "Chga", order = T, split.by = "stim")

thresh.use = 0.1
min.pct = 0
min.diff.pct = -Inf
test.use ="wilcox"

cluster.markers_all_new = FindAllMarkers(object_clean_new, logfc.threshold = thresh.use, test.use=test.use, min.pct=min.pct, min.diff.pct=min.diff.pct, only.pos=TRUE)


head(cluster.markers_all_new)

DefaultAssay(object_clean_new) = "RNA"
FeaturePlot(object_clean_new, "Ldlr", label = T)

cluster.markers_all_new[grep("Ldlr", cluster.markers_all_new$gene), ]

FeaturePlot(object_clean_new, "Pipox", label = T)

filename_xls <- 'FindAllMarkers_min.pct_0.001.xlsx'
write.xlsx(cluster.markers_all_new,
           file= filename_xls, 
           row.names = F,
           asTable = T)


head(cluster.markers_all_new)
getwd()

mg_1 = cluster.markers_all_new


mg_pvalue_1 = mg_1[mg_1$p_val_adj < 0.05, ] 
mg_avg_logFC_1 = mg_pvalue_1[mg_pvalue_1$avg_log2FC > 0, ] 

test_bis <- as.data.frame(mg_avg_logFC_1 %>%
  group_by(gene) %>%
  summarise(temp = toString(cluster)) %>%
  ungroup())



test_bis$counts <- lengths(strsplit(test_bis$temp, ","))
head(test_bis)

nrow(mg_avg_logFC_1)
nrow(test)

#library(dplyr)
#test =mg_avg_logFC_1 %>%
#     group_by(gene) %>%
#     slice(which.max(avg_log2FC))


#test = as.data.frame(test)

#head(test)
#top30 <- mg %>% group_by(cluster) %>% top_n(n = 30, wt = avg_logFC)
#table(mg_avg_logFC_1$cluster)
#mg_avg_logFC_1=subset(test, select=c("cluster", "gene"))
#head(mg_avg_logFC_1)


test_1 <- mg_avg_logFC_1 %>%
  group_by(gene) %>%
  summarise(temp = toString(cluster)) %>%
  ungroup()

head(test_1)

test_df_1 = as.data.frame(test_1)

head(test_df_1)
head(test_bis)

test_df_1 <- merge(test_df_1, test_bis, by = "gene", all.x = TRUE)

head(test_df_1)
colnames(test_df_1) = c("gene","celltype_highest_LR","celltype","number_of_diff_celltypes")
head(test_df_1)

rownames(test_df_1) = test_df_1$gene



colnames(test_df_1) =c("gene_in_sc","celltypes_highest_LR", "celltypes","number_of_diff_celltypes")


colnames(test_df_1)

test_df = (test_df_1 %>% 
    mutate(celltype_raw = ifelse(celltypes_highest_LR %in% c("FIBRO", grep("FIBRO", celltypes_highest_LR, value=T)), "FIBRO",
                  ifelse(celltypes_highest_LR %in% c(grep("BARR_END_CAP", celltypes_highest_LR, value=T),"TIP_1", "VENOUS_PLVAP-", "VENOUS_PLVAP+", "TIP_2", "ARTERIAL", "LEC", "VENOUS", "CAPILLARY_PLVAP+", "CAPILLARY_PLVAP-"), "EC",
                   ifelse(celltypes_highest_LR %in% c(grep("TIP_1", celltypes_highest_LR, value=T)), "EC",    
                  ifelse(celltypes_highest_LR %in% c(grep("NK", celltypes_highest_LR, value=T)), "NK",
                  ifelse(celltypes_highest_LR %in% c(grep("TIP_1", celltypes_highest_LR, value=T)), "EC",          
                  ifelse(celltypes_highest_LR %in% c(grep("PERI", celltypes_highest_LR, value=T)), "PERICYTES", NA))))))))

###############


test_df = (test_df_1 %>% 
    mutate(celltype_raw = ifelse(number_of_diff_celltypes > 1 , "MIX",
                  ifelse(celltypes_highest_LR %in% c(grep("BARR_END_CAP", celltypes_highest_LR, value=T),"TIP_1", "VENOUS_PLVAP-", "VENOUS_PLVAP+", "TIP_2", "ARTERIAL", "LEC", "VENOUS", "CAPILLARY_PLVAP+", "CAPILLARY_PLVAP-"), "EC",
                   ifelse(celltypes %in% c(grep("TIP_1", celltypes_highest_LR, value=T)), "EC",
                  ifelse(celltypes %in% c(grep("FIBRO", celltypes_highest_LR, value=T)), "FIBRO", 
                  ifelse(celltypes %in% c(grep("NK", celltypes_highest_LR, value=T)), "NK",
                  ifelse(celltypes %in% c(grep("TIP_1", celltypes_highest_LR, value=T)), "EC",  
                  ifelse(celltypes %in% c(grep("TIP_3", celltypes_highest_LR, value=T)), "EC",  
                  ifelse(celltypes %in% c(grep("PERI", celltypes_highest_LR, value=T)), "PERICYTES", NA))))))))))

head(test_df)


rownames(test_df) = test_df$gene_in_sc
head(test_df)
test_df[grep("Dsn1", test_df$gene_in_sc), ]

###################




DGE_cherry = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/only_KDRCherry_Combat_no_outliers/DGE_results_Cherry/DGE_results_Cherry.xlsx",
  sheet = 1,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)

head(test_df)

cherry <- merge(DGE_cherry, test_df, by = "row.names", all.x = TRUE)
head(test_df)


cherry_sort <- cherry[order(cherry$pvalue, decreasing = F),]  

SAVE_variable <- list()
filename_xls <- "DGE_results_Cherry_celltype_0.001.xlsx"
variable2save_names <- 'KO_vs_WT'


# all_counts

SAVE_variable[[variable2save_names[1]]] <- cherry_sort

# expGENES_counts


write.xlsx(SAVE_variable,
           file = "DGE_results_Cherry_celltype_0.001.xlsx", 
           row.names = F,
           asTable = F, 
           sheetName =variable2save_names)



###############################

DGE_tomato_14_vs_7 = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/combined_samples_1133_1292/DGE_results_Tomato/DGE_results_Tomato.xlsx",
  sheet = 1,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)



DGE_tomato_14_vs_intact = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/combined_samples_1133_1292/DGE_results_Tomato/DGE_results_Tomato.xlsx",
  sheet = 2,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)


DGE_tomato_7_vs_intact = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/combined_samples_1133_1292/DGE_results_Tomato/DGE_results_Tomato.xlsx",
  sheet = 3,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)


merged_1 <- merge(DGE_tomato_14_vs_7, test_df, by = "row.names", all.x = TRUE)
merged_1_sort <- merged_1[order(merged_1$pvalue, decreasing = F),]  

head(merged_1_sort)


merged_2 <- merge(DGE_tomato_14_vs_intact, test_df, by = "row.names", all.x = TRUE)
merged_2_sort <- merged_2[order(merged_2$pvalue, decreasing = F),]  


merged_3 <- merge(DGE_tomato_7_vs_intact, test_df, by = "row.names", all.x = TRUE)
merged_3_sort <- merged_3[order(merged_3$pvalue, decreasing = F),]  


SAVE_variable <- list()
filename_xls <- "DGE_results_Tomato_celltype_0.001.xlsx"
variable2save_names <- c('crush_d14_vs_crush_d7', 'crush_d14_vs_intact','crush_d7_vs_intact')


SAVE_variable[[variable2save_names[1]]] <- merged_1_sort

SAVE_variable[[variable2save_names[2]]] <- merged_2_sort

SAVE_variable[[variable2save_names[3]]] <- merged_3_sort

write.xlsx(SAVE_variable,
           file = filename_xls, 
           row.names = F,
           asTable = F, 
           sheetName =variable2save_names)


#################
#plot the average expression of the DEG
setwd("/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/")

#baseMean: mean of normalized counts for all samples
#log2FoldChange: log2 fold change
#lfcSE: standard error
#stat: Wald statistic
#pvalue: Wald test p-value
#padj: BH adjusted p-values

############

Crush_D14_vs_Crush_D7 = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/DGE_results_Tomato_celltype_0.xlsx",
  sheet = 1,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)

head(Crush_D14_vs_Crush_D7)

subset = Crush_D14_vs_Crush_D7[,c("baseMean","celltypes_highest_LR")]

head(subset)


average_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(mean(baseMean)))

sd_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(sd(baseMean)))

median_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(median(baseMean)))

top_ct = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(no_obs = n()))




merged <- merge(average_ct_exp,sd_ct_exp,by="celltypes_highest_LR")

colnames(merged) = c("celltypes_highest_LR","mean","sd")


library(ggplot2)

# Most basic error bar

setwd("/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/")

head(subset)

pdf("Crush_D14_vs_Crush_D7_baseMean.pdf", 20, 10)
p <- ggplot(subset, aes(celltypes_highest_LR, baseMean))
p + geom_boxplot() +  coord_cartesian(ylim = c(0, 50000)) + stat_summary(fun.y="mean", color="red", shape=15)
dev.off()

#pdf("Crush_D14_vs_Crush_D7_baseMean.pdf", 20, 10)
#ggplot(merged) +
#    geom_bar( aes(x=celltypes_highest_LR, y=mean), stat="identity", fill="skyblue", alpha=0.7) +
#    geom_errorbar( aes(x=celltypes_highest_LR, ymin=mean-sd, ymax=mean+sd), width=0.4, colour="orange", alpha=0.9, size=1.3) + ggtitle('Crush D14 vs Crush D7 avg mean of normalized counts and sd') + theme( axis.text.x = element_text( face = "bold", size=10))
#dev.off()


pdf("Crush_D14_vs_Crush_D7_assignedCTproportion.pdf", 20, 10)
ggplot(top_ct) +
    geom_bar( aes(x=celltypes_highest_LR, y=no_obs), stat="identity", fill="skyblue", alpha=0.7) + ggtitle('Crush D14 vs Crush D7 celltype proportion') + theme( axis.text.x = element_text( face = "bold", size=10))
dev.off()
#####

Crush_D14_vs_intact = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/DGE_results_Tomato_celltype_0.xlsx",
  sheet = 2,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)



subset = Crush_D14_vs_intact[,c("baseMean","celltypes_highest_LR")]

average_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(mean(baseMean)))

sd_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(sd(baseMean)))

median_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(median(baseMean)))

top_ct2 = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(no_obs = n()))


merged <- merge(average_ct_exp,sd_ct_exp,by="celltypes_highest_LR")

colnames(merged) = c("celltypes_highest_LR","mean","sd")

pdf("Crush_D14_vs_Intact_baseMean.pdf", 20, 10)
p <- ggplot(subset, aes(celltypes_highest_LR, baseMean))
p + geom_boxplot() +  coord_cartesian(ylim = c(0, 50000)) + stat_summary(fun.y="mean", color="red", shape=15) + ggtitle('Crush D14 vs Intact celltype proportion')
dev.off()



pdf("Crush_D14_vs_Intact_assignedCTproportion.pdf", 20, 10)
ggplot(top_ct) +
    geom_bar( aes(x=celltypes_highest_LR, y=no_obs), stat="identity", fill="skyblue", alpha=0.7) + ggtitle('Crush D14 vs Intact celltype proportion') + theme( axis.text.x = element_text( face = "bold", size=10))
dev.off()


################################

#####

Crush_D7_vs_intact = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/DGE_results_Tomato_celltype_0.xlsx",
  sheet = 3,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)

subset = Crush_D7_vs_intact[,c("baseMean","celltypes_highest_LR")]

average_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(mean(baseMean)))

sd_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(sd(baseMean)))

median_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(median(baseMean)))

top_ct2 = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(no_obs = n()))


merged <- merge(average_ct_exp,sd_ct_exp,by="celltypes_highest_LR")

colnames(merged) = c("celltypes_highest_LR","mean","sd")

pdf("Crush_D7_vs_Intact_baseMean.pdf", 20, 10)
p <- ggplot(subset, aes(celltypes_highest_LR, baseMean))
p + geom_boxplot() +  coord_cartesian(ylim = c(0, 50000)) + stat_summary(fun.y="mean", color="red", shape=15) + ggtitle('Crush D7 vs Intact celltype proportion')
dev.off()


pdf("Crush_D7_vs_Intact_assignedCTproportion.pdf", 20, 10)
ggplot(top_ct) +
    geom_bar( aes(x=celltypes_highest_LR, y=no_obs), stat="identity", fill="skyblue", alpha=0.7) + ggtitle('Crush D7 vs Intact celltype proportion') + theme( axis.text.x = element_text( face = "bold", size=10))
dev.off()

########

################################

#####

Cherry = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/DGE_results_Cherry_celltype_0.xlsx",
  sheet = 1,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)

subset = Cherry[,c("baseMean","celltypes_highest_LR")]

average_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(mean(baseMean)))

sd_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(sd(baseMean)))

median_ct_exp = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(median(baseMean)))

top_ct2 = as.data.frame(subset %>%
    group_by(celltypes_highest_LR) %>%
    summarize(no_obs = n()))


merged <- merge(average_ct_exp,sd_ct_exp,by="celltypes_highest_LR")

colnames(merged) = c("celltypes_highest_LR","mean","sd")

pdf("Crush_KO_vs_WT_baseMean.pdf", 20, 10)
p <- ggplot(subset, aes(celltypes_highest_LR, baseMean))
p + geom_boxplot() +  coord_cartesian(ylim = c(0, 50000)) + stat_summary(fun.y="mean", color="red", shape=15) + ggtitle('Crush KO_vs_WT celltype proportion')
dev.off()


pdf("Crush_KO_vs_WT_assignedCTproportion.pdf", 20, 10)
ggplot(top_ct2) +
    geom_bar( aes(x=celltypes_highest_LR, y=no_obs), stat="identity", fill="skyblue", alpha=0.7) + ggtitle('Crush KO_vs_WT celltype proportion') + theme( axis.text.x = element_text( face = "bold", size=10))
dev.off()




####################

RPKM_Tomato = read.xlsx(
  "/Users/maurizio.aurora/Dropbox (HSR Global)/WORKSPACE/Bonanomi/BonanomiD_1292_RNASeq/7_bioinfo/deconvolution/Associate_celltype_with_gene_name/DGE_results_Tomato_celltype_0.xlsx",
  sheet = 3,
  startRow = 1,
  colNames = TRUE,
  rowNames = TRUE,
)





